title: Epistemology, Metaphysics, Ethics, and Art
email: wei.ge.thoughts@gmail.com
description: A collection of my essays about epistemology, metaphysics, ethics, and art.
baseurl: ""
url: ""

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  essays:
    output: true
    permalink: /:path
defaults:
  - scope:
      path: ""
      type: essays
    values:
      layout: essay
