title: Art, History, Ethics, Epistemology, and Metaphysics
email: artsandmetaphysics@gmail.com
description: My essays about art, history, ethics, epistemology, and metaphysics
baseurl: ""
url: "http://artsandmetaphysics.com"

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  documents:
    output: true
    permalink: /:path
defaults:
  - scope:
      path: ""
      type: documents
    values:
      layout: basic
      status: complete
