title: Art, Ethic, Epistemology, and Metaphysics
email: wei.ge.thoughts@gmail.com
description: My essays about art, ethics, epistemology, and metaphysics
baseurl: "http://artsandmetaphysics.com"
url: ""

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  essays:
    output: true
    permalink: /:path
defaults:
  - scope:
      path: ""
      type: essays
    values:
      layout: basic
      status: complete
