title: Art, History, Religion, and Philosophy
email: artsandmetaphysics@gmail.com
description: Essays and notes about literature, history, religion, and philosophy.
baseurl: ""
url: "http://artsandmetaphysics.com"

markdown: kramdown
theme: minima
permalink: /meditations/:year/:i_month/:title
config:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
include:
  - sitemap.txt
collections:
  documents:
    output: true
    permalink: /:path
defaults:
  - scope:
      path: ""
    values:
      layout: basic
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
plugins_dir:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
