title: Art, History, Religion, and Philosophy
email: artsandmetaphysics@gmail.com
description: My essays and notes about art, history, religion, and philosophy.
baseurl: ""
url: "https://artsandmetaphysics.com"

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  documents:
    output: true
    permalink: /:path
defaults:
  - scope:
      path: ""
      type: documents
    values:
      layout: basic
      status: complete
plugins:
  - jekyll-sitemap
